name : Terraform_build
trigger:
 - none
pool :
 vmImage : windows-latest


stages:
- stage: Terraform_init_validate
  jobs:
    - job: Terraform_init_validate
      steps:
      - task: TerraformInstaller@0
        inputs: 
          terraformVersion: 'latest' 
      - task: TerraformTaskV3@3
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          backendServiceArm: 'Dev-sub'
          backendAzureRmResourceGroupName: 'test-tstate-rg'
          backendAzureRmStorageAccountName: 'testcloudtfstate15439'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'test.devops.tfstate'
      - task: TerraformTaskV3@3
        inputs: 
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          environmentServiceNameAzureRM: 'Dev-sub'

- stage: Terraform_plan 
  jobs:
    - job: Terraform_plan
      steps:

      - task: TerraformInstaller@0
        inputs: 
          terraformVersion: 'latest' 
      - task: TerraformTaskV3@3
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/code'
          backendServiceArm: 'Dev-sub'
          backendAzureRmResourceGroupName: 'test-tstate-rg'
          backendAzureRmStorageAccountName: 'testcloudtfstate15439'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'test.devops.tfstate'           
      - task: TerraformTaskV3@3
        inputs:
          provider: 'azurerm' 
          command: 'plan -var-file="dev.tfvars'
          workingDirectory: '$(System.DefaultWorkingDirectory)/code'
          environmentServiceNameAzureRM: 'Dev-sub'
        
        
- stage: Terraform_apply
  jobs:
    - job: Terraform_apply
      steps:
      - task: TerraformInstaller@0
        inputs: 
          terraformVersion: 'latest' 
      - task: TerraformTaskV3@3
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          backendServiceArm: 'Dev-sub'
          backendAzureRmResourceGroupName: 'test-tstate-rg'
          backendAzureRmStorageAccountName: 'testcloudtfstate15439'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'test.devops.tfstate'    
      - task: TerraformTaskV3@3
        inputs:
          provider: 'azurerm'
          command: 'apply'
          environmentServiceNameAzureRM: 'Dev-sub'