resource_group             = "vmss-eastus-rg"
location                   = "eastus"
vnet_name                  = "vnet-deploy"
sg_name                    = "local-deply-sg"
packer_resource_group_name = "myResourceGroup"
packer_image_name          = "PackerImagev4"
admin_password             = "Darkknight@123"
size                       = "Standard_F2"
